# Preprocessing and Training

In [3]:
#importing modules 

import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [5]:
# loading into the dataframe 

df = pd.read_csv('preprocessing.csv')
df.head()

,Name,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Genre,Publisher,platforms,Years_of_Release,...,Fighting,Misc,Platform,Puzzle,Racing,Role-Playing,Shooter,Simulation,Sports,Strategy
0,Wii Sports,41.36,28.96,3.77,8.45,82.54,Sports,Nintendo,1,11.0,...,0,0,0,0,0,0,0,0,1,0
1,Grand Theft Auto V,24.13,24.14,1.43,8.04,57.75,Action,Take-Two Interactive,7,3.0,...,0,0,0,0,0,0,0,0,0,0
2,Super Mario Bros.,32.48,4.88,6.96,0.99,45.31,Platform,Nintendo,8,25.0,...,0,0,1,0,0,0,0,0,0,0
3,Mario Kart Wii,15.68,12.80,3.79,3.29,35.57,Racing,Nintendo,1,9.0,...,0,0,0,0,1,0,0,0,0,0
4,Wii Sports Resort,15.61,10.95,3.28,2.95,32.78,Sports,Nintendo,1,8.0,...,0,0,0,0,0,0,0,0,1,0

In [6]:
df.columns

Index(['Name', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales',
       'Global_Sales', 'Genre', 'Publisher', 'platforms', 'Years_of_Release',
       'Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy'],
      dtype='object')

In [10]:
# defining variables 

X0 = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'platforms', 'Years_of_Release',
       'Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy']]
X1 = df[['EU_Sales', 'JP_Sales', 'Other_Sales', 'platforms', 'Years_of_Release',
       'Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy']]
X2 = df[['NA_Sales', 'JP_Sales', 'Other_Sales', 'platforms', 'Years_of_Release',
       'Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy']]
X3 = df[['EU_Sales', 'NA_Sales', 'Other_Sales', 'platforms', 'Years_of_Release',
       'Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy']]

y0 = df['Global_Sales']
y1 = df['NA_Sales']
y2 = df['EU_Sales']
y3 = df['JP_Sales']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X0, y0, test_size = 0.2)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(4991, 18) (4991,) (1248, 18) (1248,)